### ISSUE TITLE
Erro de atualização dos containers do docker

### ISSUE THREAD

**Issue by isaacvits** [servicosgovbr/docker#12]
Toda vez que é executado o script de update dos containers do docker, acontece um erro no DeviceMapper e os containers não são atualizados.

**Comment by isaacvits** [comment]
Foi feito teste com o storage driver overlay no centOS 7.1 e a atualização dos containers foi feita com sucesso, o próximo passo será fazer o teste do overlay em um ambiente igual o de produção.

**Comment by almeidafab** [comment]
@isaacvits foi realizado um teste no ambiente igual ao de produção (Centos 7.2) e houve uma falha no overlay na hora de remover os containers. @cv @gustavo-freitas Estamos pensando em fazer um downgrade para a mesma versão de desenvolvimento. Vocês enxergam algum problema em fazer isso? Tem algum motivo especial para ficarmos no CentOS 7.2?

**Comment by isaacvits** [comment]
@almeidafab  verificamos que o erro ocorre apenas na primeira atualização. Uma solução de contorno é tentar remover os containers do portal e do editor na primeira vez e depois subi-los novamente. Isso faz com que o problema não se repita nas próximas atualizações.

**Comment by caduvieira** [comment]
Isso é tanto para overlay como para o devicemapper?

Em 29 de fevereiro de 2016 16:16, isaacvits notifications@github.com
escreveu:

**Comment by isaacvits** [comment]
@caduvieira sim, isso deve ser feito para os dois.

**Comment by gomex** [comment]
Olá pessoal, você por favor poderiam postar alguns prints de erro ou logs do que está acontecendo quando se tenta remover e/ou atualizar os containers?

**Comment by isaacvits** [comment]
Vamos continuar com o DeviceMapper e mudar o modo de loop-lvm para direct-lvm, transferir para issue servicosgovbr/docker#19
