### ISSUE TITLE
Alterar os scripts de atualização

### ISSUE THREAD

**Issue by isaacvits** [servicosgovbr/docker#14]
Alterar os scripts de atualização dos portal e do editor, para atualizar os containers um por vez, primeiro portal1 e editor1 e depois o portal2 e editor2.

**Comment by isaacvits** [comment]
Foram alterados os scripts update_portal_container e update_editor_container

**Comment by cv** [comment]
Commits relacionados:

https://github.com/servicosgovbr/docker/commit/43ca7b49b46d305a18a123a519df4c657ea0c8bf
https://github.com/servicosgovbr/docker/commit/2c14685773807330706d4a7740b46a9e75e05c64
https://github.com/servicosgovbr/docker/commit/310a3a46641c82b80ef7da488da9bc018148b387
