### ISSUE TITLE
Descartar logs velhos

### ISSUE THREAD

**Issue by cv** [servicosgovbr/docker#2]
Não temos nenhuma rotina de limpeza dos indices de logs velhos no ElasticSearch. Se o sistema for usado de forma muito pesada (sofrer um DDoS, por exemplo), ou durante muito tempo, podemos ficar sem disco à toa.

**Comment by gomex** [comment]
logrotate! \o/

**Comment by gomex** [comment]
Você pode rotacionar por tamanho, inclusive :)

**Comment by cv** [comment]
Logrotate saberia jogar fora logs no Logstash/ElasticSearch?

**Comment by gomex** [comment]
Ainda não usei realmente o logstash e ES, mas se for arquivo, ele faz sim :)

Encontrei isso aqui:
https://discuss.elastic.co/t/logstash-logrotate/2530

**Comment by caduvieira** [comment]
Pelo que entendi isso é para o log do próprio logstash.

IMHO poderiamos usar o curator e apagar os logs antigos que estão armazenados nos índices do ES.

Não encontrei imagem oficial mas essa é a mais utilizada atualmente.
https://hub.docker.com/r/bobrik/curator/

E alguns exemplos em https://www.elastic.co/guide/en/elasticsearch/client/curator/current/examples.html

https://www.elastic.co/blog/curator-tending-your-time-series-indices
