### ISSUE TITLE
Não reiniciar o balanceador ao atualizar portal e editor

### ISSUE THREAD

**Issue by cv** [servicosgovbr/docker#4]
Hoje os scripts/snap-deploy-alpha têm que reinicializar o balanceador, pois o haproxy não está entendendo o sinal de que o serviço voltou ao ar, aparentemente.

O ideal seria fazer um redeploy do portal1, aguardar e verificar que ele voltou ao ar, e aí sim fazer a atualização do portal2 (idem para editor1/editor2).

**Comment by isaacvits** [comment]
@cv nós fizemos uma alteração nos scripts que atualizam o portal no ambiente de produção que primeiro atualiza o portal1 e depois o portal2 (o mesmo com o editor1 e editor2). Usamos o comando sleep entre a atualização dos containers, será que essa é a melhor forma?  [script do portal](https://github.com/servicosgovbr/docker/blob/master/scripts/update_portal_container)

**Comment by isaacvits** [comment]
Os scripts já foram alterados para atualizar um container por vez
